defaults:
  - _self_
  - data: default
  - model: default
  - optimizer: adamw
  - trainer: train
  - decode: default

hydra:
  output_subdir: null
  run:
    dir: .
exp_dir: null
mouth_dir: null
wav_dir: null
label_flag: 1
exp_name: null
gpus: null
slurm_job_id: null
file_path: null
ckpt_path: null
pretrained_model_path: null
transfer_frontend: null
transfer_encoder: null